from settings.views.button_headings.armenian_button_headings import ArmenianButtonHeadings
from settings.views.button_headings.belarusian_button_headings import BelarusianButtonHeadings
from settings.views.button_headings.chinese_button_headings import ChineseButtonHeadings
from settings.views.button_headings.english_button_headings import EnglishButtonHeadings
from settings.views.button_headings.french_button_headings import FrenchButtonHeadings
from settings.views.button_headings.georgian_button_headings import GeorgianButtonHeadings
from settings.views.button_headings.german_button_headings import GermanButtonHeadings
from settings.views.button_headings.hebrew_button_headings import HebrewButtonHeadings
from settings.views.button_headings.kazakh_button_headings import KazakhButtonHeadings
from settings.views.button_headings.portuguese_button_headings import PortugueseButtonHeadings
from settings.views.button_headings.russian_button_headings import RussianButtonHeadings
from settings.views.button_headings.spanish_button_headings import SpanishButtonHeadings
from settings.views.button_headings.turkish_button_headings import TurkishButtonHeadings
from settings.views.button_headings.ukrainian_button_headings import UkrainianButtonHeadings


LANGUAGES_BUTTON_HEADINGS = {"RUSSIAN": RussianButtonHeadings,
                        "CHINESE": ChineseButtonHeadings,
                        "ENGLISH": EnglishButtonHeadings,
                        "FRENCH": FrenchButtonHeadings,
                        "GERMAN": GermanButtonHeadings,
                        "SPANISH": SpanishButtonHeadings,
                        "PORTUGUESE": PortugueseButtonHeadings,
                        "UKRAINIAN": UkrainianButtonHeadings,
                        "BELARUSIAN": BelarusianButtonHeadings,
                        "KAZAKH": KazakhButtonHeadings,
                        "GEORGIAN": GeorgianButtonHeadings,
                        "ARMENIAN": ArmenianButtonHeadings,
                        "HEBREW": HebrewButtonHeadings,
                        "TURKISH": TurkishButtonHeadings}


class ButtonHeadings:
    """"""
    def __init__(self, language: str) -> None:
        self.MAIN_MENU_HEADING = "Меню"
        self.RUSSIAN_LANGUAGE_HEADING = "Русский"
        self.CHINESE_LANGUAGE_HEADING = "中文"
        self.ENGLISH_LANGUAGE_HEADING = "English"
        self.FRENCH_LANGUAGE_HEADING = "Français"
        self.GERMAN_LANGUAGE_HEADING = "Deutsch"
        self.SPANISH_LANGUAGE_HEADING = "Español"
        self.PORTUGUESE_LANGUAGE_HEADING = "Português"
        self.UKRAINIAN_LANGUAGE_HEADING = "Український"
        self.BELARUSIAN_LANGUAGE_HEADING = "Беларускі"
        self.KAZAKH_LANGUAGE_HEADING = "Qazaq"
        self.GEORGIAN_LANGUAGE_HEADING = "ქართული"
        self.ARMENIAN_LANGUAGE_HEADING = "Հայերեն"
        self.HEBREW_LANGUAGE_HEADING = "עברית"
        self.TURKISH_LANGUAGE_HEADING = "Türk"

        self.TIME_ZONE_UTC_MINUS12 = "UTC-12"
        self.TIME_ZONE_UTC_MINUS11 = "UTC-11"
        self.TIME_ZONE_UTC_MINUS10 = "UTC-10"
        self.TIME_ZONE_UTC_MINUS09 = "UTC-09"
        self.TIME_ZONE_UTC_MINUS08 = "UTC-08"
        self.TIME_ZONE_UTC_MINUS07 = "UTC-07"
        self.TIME_ZONE_UTC_MINUS06 = "UTC-06"
        self.TIME_ZONE_UTC_MINUS05 = "UTC-05"
        self.TIME_ZONE_UTC_MINUS04 = "UTC-04"
        self.TIME_ZONE_UTC_MINUS03 = "UTC-03"
        self.TIME_ZONE_UTC_MINUS02 = "UTC-02"
        self.TIME_ZONE_UTC_MINUS01 = "UTC-01"
        self.TIME_ZONE_UTC_PLUS00 = "UTC+00"
        self.TIME_ZONE_UTC_PLUS01 = "UTC+01"
        self.TIME_ZONE_UTC_PLUS02 = "UTC+02"
        self.TIME_ZONE_UTC_PLUS03 = "UTC+03"
        self.TIME_ZONE_UTC_PLUS04 = "UTC+04"
        self.TIME_ZONE_UTC_PLUS05 = "UTC+05"
        self.TIME_ZONE_UTC_PLUS06 = "UTC+06"
        self.TIME_ZONE_UTC_PLUS07 = "UTC+07"
        self.TIME_ZONE_UTC_PLUS08 = "UTC+08"
        self.TIME_ZONE_UTC_PLUS09 = "UTC+09"
        self.TIME_ZONE_UTC_PLUS10 = "UTC+10"
        self.TIME_ZONE_UTC_PLUS11 = "UTC+11"
        self.TIME_ZONE_UTC_PLUS12 = "UTC+12"

        self.BACK_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BACK_HEADING
        self.MAIN_MENU_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MAIN_MENU_HEADING
        #client_main_menu buttons
        self.NEW_ORDER_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_ORDER_HEADING
        self.ACTIVE_ORDERS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ACTIVE_ORDERS_HEADING
        self.MY_PROFILE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MY_PROFILE_HEADING
        self.BALANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BALANCE_HEADING
        self.SUPPORT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SUPPORT_HEADING
        self.REVIEWS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].REVIEWS_HEADING
        self.AFFILIATE_PROGRAM_HEADING = LANGUAGES_BUTTON_HEADINGS[language].AFFILIATE_PROGRAM_HEADING
        self.SOLVER_MENU_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SOLVER_MENU_HEADING

        self.CONTROL_PANEL_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CONTROL_PANEL_HEADING
        self.CUSTOM_MENU_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CUSTOM_MENU_HEADING
        self.YES_BUTTON_HEADING = LANGUAGES_BUTTON_HEADINGS[language].YES_BUTTON_HEADING
        self.NO_BUTTON_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NO_BUTTON_HEADING
        self.USER_SUBSCRIPTION_CHECK_HEADING = LANGUAGES_BUTTON_HEADINGS[language].USER_SUBSCRIPTION_CHECK_HEADING

        #new order menu
        self.NEW_ORDER_BY_ADMIN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_ORDER_BY_ADMIN_HEADING
        self.NEW_ORDER_BY_BOT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_ORDER_BY_BOT_HEADING
        self.UNFINISHED_ORDER_HEADING = LANGUAGES_BUTTON_HEADINGS[language].UNFINISHED_ORDER_HEADING
        #new order menu:    order format
        self.STANDART_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].STANDART_IMPORTANCE_HEADING
        self.NOW_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NOW_IMPORTANCE_HEADING
        self.IMPORTANT_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].IMPORTANT_IMPORTANCE_HEADING
        self.VOLUMINOUS_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].VOLUMINOUS_IMPORTANCE_HEADING
        #new order menu:    standart order main menu
        self.NEW_STANDART_ORDER_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_STANDART_ORDER_IMPORTANCE_HEADING
        self.NEW_NOW_ORDER_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_NOW_ORDER_IMPORTANCE_HEADING
        self.NEW_IMPORTANT_ORDER_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_IMPORTANT_ORDER_IMPORTANCE_HEADING
        self.NEW_VOLUMINOUS_ORDER_IMPORTANCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_VOLUMINOUS_ORDER_IMPORTANCE_HEADING
        self.NEW_STANDART_ORDER_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_STANDART_ORDER_SUBJECT_HEADING
        self.NEW_STANDART_ORDER_COMMENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_STANDART_ORDER_COMMENT_HEADING
        self.NEW_STANDART_ORDER_FILES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_STANDART_ORDER_FILES_HEADING
        self.NEW_STANDART_ORDER_DEADLINE_TIME_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_STANDART_ORDER_DEADLINE_TIME_HEADING
        self.NEW_IMPORTANT_ORDER_DURATION_TIME_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_IMPORTANT_ORDER_DURATION_TIME_HEADING
        self.NEW_NOW_ORDER_NUMBER_OF_TASKS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NEW_NOW_ORDER_NUMBER_OF_TASKS_HEADING
        self.UP_ORDER_SETTINGS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].UP_ORDER_SETTINGS_HEADING
        self.SEND_ORDER_TO_SOLVERS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SEND_ORDER_TO_SOLVERS_HEADING
        #get order time
        self.GET_ORDER_TIME_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GET_ORDER_TIME_HEADING
        self.ORDER_1DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_1DURATION_HEADING
        self.ORDER_2DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_2DURATION_HEADING
        self.ORDER_3DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_3DURATION_HEADING
        self.ORDER_4DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_4DURATION_HEADING
        self.ORDER_5DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_5DURATION_HEADING
        self.ORDER_6DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_6DURATION_HEADING
        self.ORDER_7DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_7DURATION_HEADING
        self.ORDER_8DURATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORDER_8DURATION_HEADING
        #get order files
        self.CONFIRM_FILES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CONFIRM_FILES_HEADING
        self.DELETE_ALL_FILES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DELETE_ALL_FILES_HEADING
        #order formats
        self.CONTROL_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CONTROL_FORMAT_HEADING
        self.HOMEWORK_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].HOMEWORK_FORMAT_HEADING
        self.EXAM_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].EXAM_FORMAT_HEADING
        self.LABA_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LABA_FORMAT_HEADING
        self.COURSEWORK_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].COURSEWORK_FORMAT_HEADING
        self.DIPLOMA_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DIPLOMA_FORMAT_HEADING
        self.OTHER_FORMAT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_FORMAT_HEADING
        #order percent complete
        self.TEN_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TEN_PERCENT_HEADING
        self.TWENTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TWENTY_PERCENT_HEADING
        self.THIRTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].THIRTY_PERCENT_HEADING
        self.FORTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FORTY_PERCENT_HEADING
        self.FIFTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FIFTY_PERCENT_HEADING
        self.SIXTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SIXTY_PERCENT_HEADING
        self.SEVENTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SEVENTY_PERCENT_HEADING
        self.EIGHTY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].EIGHTY_PERCENT_HEADING
        self.NINETY_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].NINETY_PERCENT_HEADING
        self.HUNDRED_PERCENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].HUNDRED_PERCENT_HEADING


        #additional order settings menu
        self.SUPPORT_ORDER_SETTING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SUPPORT_ORDER_SETTING_HEADING
        self.PERCENT_COMPLET_ORDER_SETTING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PERCENT_COMPLET_ORDER_SETTING_HEADING
        self.PREFERRED_BUDGET_ORDER_SETTING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PREFERRED_BUDGET_ORDER_SETTING_HEADING
        self.TYPE_ORDER_SETTING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TYPE_ORDER_SETTING_HEADING
        #check order complite to send menu


        """Orders and topics keyboards:"""
        self.MATHS_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATHS_SUBJECT_HEADING
        self.PHYSICS_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PHYSICS_SUBJECT_HEADING
        self.IT_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].IT_SUBJECT_HEADING
        self.ENGINEERING_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ENGINEERING_SUBJECT_HEADING
        self.ECONOMY_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ECONOMY_SUBJECT_HEADING
        self.CHEMISTRY_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CHEMISTRY_SUBJECT_HEADING
        self.LANGUAGES_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LANGUAGES_SUBJECT_HEADING
        self.BIOLOGY_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BIOLOGY_SUBJECT_HEADING
        self.GEOGRAPHY_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GEOGRAPHY_SUBJECT_HEADING
        self.HUMANITARIAN_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].HUMANITARIAN_SUBJECT_HEADING
        self.REGISTRATION_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].REGISTRATION_SUBJECT_HEADING
        self.OTHER_SUBJECT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_SUBJECT_HEADING

        #maths topic keyboard
        self.CALCULUS_OF_VARIATIONS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CALCULUS_OF_VARIATIONS_HEADING
        self.VECTOR_TENSOR_ANALYSIS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].VECTOR_TENSOR_ANALYSIS_HEADING
        self.COMPUTATIONAL_MATHEMATICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].COMPUTATIONAL_MATHEMATICS_HEADING
        self.DISCRETE_MATHEMATICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DISCRETE_MATHEMATICS_HEADING
        self.DIFFUSIONS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DIFFUSIONS_HEADING
        self.MULTIPLE_INTEGRALS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MULTIPLE_INTEGRALS_HEADING
        self.MATHEMATICAL_ANALYSIS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATHEMATICAL_ANALYSIS_HEADING
        self.MATHEMATICAL_MODELING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATHEMATICAL_MODELING_HEADING
        self.SYSTEM_ANALYSIS_AND_DECISION_MAKING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SYSTEM_ANALYSIS_AND_DECISION_MAKING_HEADING
        self.TFCP_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TFCP_HEADING
        self.ANALYTICAL_GEOMETRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ANALYTICAL_GEOMETRY_HEADING
        self.LINEAR_ALGEBRA_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LINEAR_ALGEBRA_HEADING
        self.MATHEMATICAL_STATISTICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATHEMATICAL_STATISTICS_HEADING
        self.ROWS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ROWS_HEADING
        self.PROBABILITY_THEORY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PROBABILITY_THEORY_HEADING
        self.TOPOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TOPOLOGY_HEADING
        self.UMF_HEADING = LANGUAGES_BUTTON_HEADINGS[language].UMF_HEADING
        self.FUNCTIONAL_ANALYSIS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FUNCTIONAL_ANALYSIS_HEADING
        self.FUNCTIONS_OF_MULTIPLE_VARIABLES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FUNCTIONS_OF_MULTIPLE_VARIABLES_HEADING
        self.OTHER_MATHS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_MATHS_HEADING
        #physics topic keyboard
        self.QUANTUM_MECHANICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].QUANTUM_MECHANICS_HEADING
        self.MATERIALS_SCIENCE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATERIALS_SCIENCE_HEADING
        self.METROLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].METROLOGY_HEADING
        self.MECHANICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MECHANICS_HEADING
        self.FLUID_AND_GAS_MECHANICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FLUID_AND_GAS_MECHANICS_HEADING
        self.OPTICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OPTICS_HEADING
        self.STRENGTH_OF_MATERIALS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].STRENGTH_OF_MATERIALS_HEADING
        self.THEORETICAL_MECHANICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].THEORETICAL_MECHANICS_HEADING
        self.ELECTRICITY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ELECTRICITY_HEADING
        self.OTHER_PHYSICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_PHYSICS_HEADING
        #IT topic keyboards
        self.BASIC_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BASIC_IT_HEADING
        self.C_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].C_IT_HEADING
        self.C_SHARP_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].C_SHARP_IT_HEADING
        self.C_PLUS_PLUS_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].C_PLUS_PLUS_IT_HEADING
        self.DELPHI_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DELPHI_IT_HEADING
        self.EXCEL_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].EXCEL_IT_HEADING
        self.JAVA_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].JAVA_IT_HEADING
        self.JAVA_SCRIPT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].JAVA_SCRIPT_HEADING
        self.GO_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GO_IT_HEADING
        self.MATLAB_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MATLAB_IT_HEADING
        self.PYTHON_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PYTHON_IT_HEADING
        self.PHP_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PHP_IT_HEADING
        self.DATA_BASE_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DATA_BASE_IT_HEADING
        self.LATEX_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LATEX_IT_HEADING
        self.LAZARUS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LAZARUS_HEADING
        self.PASCAL_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PASCAL_IT_HEADING
        self.R_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].R_IT_HEADING
        self.OTHER_IT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_IT_HEADING
        #engineering
        self.ENGINEERING_GRAPHICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ENGINEERING_GRAPHICS_HEADING
        self.DESCRIPTIVE_GEOMETRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DESCRIPTIVE_GEOMETRY_HEADING
        self.CIRCUITRY_AND_MECHATRONICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CIRCUITRY_AND_MECHATRONICS_HEADING
        self.THEORY_OF_MECHANISMS_AND_MACHINES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].THEORY_OF_MECHANISMS_AND_MACHINES_HEADING
        self.TECHNOLOGY_OF_STRUCTURAL_MATERIALS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TECHNOLOGY_OF_STRUCTURAL_MATERIALS_HEADING
        self.ELECTRONICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ELECTRONICS_HEADING
        self.ELECTRONIC_BOARDS_AND_COMPONENTS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ELECTRONIC_BOARDS_AND_COMPONENTS_HEADING
        self.ELECTRICAL_ENGINEERING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ELECTRICAL_ENGINEERING_HEADING
        self.ANALYTICAL_MECHANICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ANALYTICAL_MECHANICS_HEADING
        self.MACHINES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MACHINES_HEADING
        self.OTHER_ENGINEERING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_ENGINEERING_HEADING
        #economy
        self.LOGISTICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LOGISTICS_HEADING
        self.MACROECONOMICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MACROECONOMICS_HEADING
        self.MARKETING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MARKETING_HEADING
        self.MANAGEMENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MANAGEMENT_HEADING
        self.MICROECONOMICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MICROECONOMICS_HEADING
        self.TAXATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].TAXATION_HEADING
        self.PERSONNEL_MANAGEMENT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PERSONNEL_MANAGEMENT_HEADING
        self.ECONOMY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ECONOMY_HEADING
        self.ACCOUNTING_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ACCOUNTING_HEADING
        self.ECONOMETRICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ECONOMETRICS_HEADING
        self.OTHER_ECONOMY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_ECONOMY_HEADING
        #chemistry
        self.ORGANIC_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ORGANIC_CHEMISTRY_HEADING
        self.ANALYTICAL_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ANALYTICAL_CHEMISTRY_HEADING
        self.GENERAL_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GENERAL_CHEMISTRY_HEADING
        self.BIOCHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BIOCHEMISTRY_HEADING
        self.PHYSICAL_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PHYSICAL_CHEMISTRY_HEADING
        self.INORGANIC_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].INORGANIC_CHEMISTRY_HEADING
        self.OTHER_CHEMISTRY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_CHEMISTRY_HEADING
        #languages
        self.RUSSIAN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].RUSSIAN_HEADING
        self.CHINESE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CHINESE_HEADING
        self.ENGLISH_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ENGLISH_HEADING
        self.FRENCH_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FRENCH_HEADING
        self.GERMAN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GERMAN_HEADING
        self.SPANISH_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SPANISH_HEADING
        self.OTHER_LANGUAGES_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_LANGUAGES_HEADING
        #biology
        self.ANATOMY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ANATOMY_HEADING
        self.PARASITOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PARASITOLOGY_HEADING
        self.BIOINFORMATICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BIOINFORMATICS_HEADING
        self.MICROBIOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MICROBIOLOGY_HEADING
        self.BOTANY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BOTANY_HEADING
        self.MOLECULAR_BIOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].MOLECULAR_BIOLOGY_HEADING
        self.ZOOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ZOOLOGY_HEADING
        self.GENETICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GENETICS_HEADING
        self.VIROLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].VIROLOGY_HEADING
        self.OTHER_BIOLOGY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_BIOLOGY_HEADING
        #geography
        self.GEOGRAPHY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].GEOGRAPHY_HEADING
        #humanitarian
        self.HISTORY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].HISTORY_HEADING
        self.DESIGN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].DESIGN_HEADING
        self.OBZH_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OBZH_HEADING
        self.PHILOSOPHY_HEADING = LANGUAGES_BUTTON_HEADINGS[language].PHILOSOPHY_HEADING
        self.LAW_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LAW_HEADING
        self.OTHER_HUMANITARIAN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].OTHER_HUMANITARIAN_HEADING
        #registration
        self.REGISTRATION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].REGISTRATION_HEADING


        """"""

        #my profile menu
        self.SET_BANKING_DETAILS_HEADINGS = LANGUAGES_BUTTON_HEADINGS[language].SET_BANKING_DETAILS_HEADINGS
        self.SET_CURRENCY_HEADINGS = LANGUAGES_BUTTON_HEADINGS[language].SET_CURRENCY_HEADINGS
        self.SET_LANGUAGE_HEADING = LANGUAGES_BUTTON_HEADINGS[language].SET_LANGUAGE_HEADING

        #balance menu
        self.CASH_IN_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CASH_IN_HEADING
        self.CASH_OUT_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CASH_OUT_HEADING

        #support menu
        self.BECOME_A_PARTNER_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BECOME_A_PARTNER_HEADING
        self.BECOME_A_SOLVER_HEADING = LANGUAGES_BUTTON_HEADINGS[language].BECOME_A_SOLVER_HEADING
        self.ASK_A_QUESTION_HEADING = LANGUAGES_BUTTON_HEADINGS[language].ASK_A_QUESTION_HEADING
        self.FAQ_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FAQ_HEADING
        #support FAQ menu
        self.FAQ_FOR_CLIENTS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FAQ_FOR_CLIENTS_HEADING
        self.FAQ_FOR_SOLVERS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FAQ_FOR_SOLVERS_HEADING
        self.FAQ_FOR_PARTNERS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].FAQ_FOR_PARTNERS_HEADING

        #affiliate program menu
        self.LIST_AFFILIATE_LINKS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].LIST_AFFILIATE_LINKS_HEADING
        self.CREATE_AFFILIATE_LINK_HEADING = LANGUAGES_BUTTON_HEADINGS[language].CREATE_AFFILIATE_LINK_HEADING
        self.AFFILIATE_PROGRAM_STATISTICS_HEADING = LANGUAGES_BUTTON_HEADINGS[language].AFFILIATE_PROGRAM_STATISTICS_HEADING



class ButtonCallbackData:
    #speshial
    BACK_CALLBACK_DATA = "BACK_CALLBACK_DATA_btn_back"
    RUSSIAN_LANGUAGE_CALLBACK_DATA = "RUSSIAN"
    CHINESE_LANGUAGE_CALLBACK_DATA = "CHINISE"
    ENGLISH_LANGUAGE_CALLBACK_DATA = "ENGLISH"
    FRENCH_LANGUAGE_CALLBACK_DATA = "FRENCH"
    GERMAN_LANGUAGE_CALLBACK_DATA = "GERMAN"
    SPANISH_LANGUAGE_CALLBACK_DATA = "SPANISH"
    PORTUGUESE_LANGUAGE_CALLBACK_DATA = "PORTUGUESE"
    UKRAINIAN_LANGUAGE_CALLBACK_DATA = "UKRAINIAN"
    BELARUSIAN_LANGUAGE_CALLBACK_DATA = "BELARUSIAN"
    KAZAKH_LANGUAGE_CALLBACK_DATA = "KAZAKH"
    GEORGIAN_LANGUAGE_CALLBACK_DATA = "GEORGIAN"
    ARMENIAN_LANGUAGE_CALLBACK_DATA = "ARMENIAN"
    HEBREW_LANGUAGE_CALLBACK_DATA = "HEBREW"
    TURKISH_LANGUAGE_CALLBACK_DATA = "TURKISH"

    TIME_ZONE_UTC_MINUS12_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS12_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS11_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS11_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS10_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS10_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS09_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS09_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS08_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS08_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS07_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS07_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS06_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS07_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS05_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS05_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS04_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS04_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS03_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS03_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS02_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS02_CALLBACK_DATA"
    TIME_ZONE_UTC_MINUS01_CALLBACK_DATA = "TIME_ZONE_UTC_MINUS01_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS00_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS00_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS01_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS01_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS02_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS02_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS03_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS03_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS04_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS04_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS05_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS05_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS06_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS06_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS07_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS07_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS08_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS08_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS09_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS09_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS10_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS10_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS11_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS11_CALLBACK_DATA"
    TIME_ZONE_UTC_PLUS12_CALLBACK_DATA = "TIME_ZONE_UTC_PLUS12_CALLBACK_DATA"

    #client_main_menu buttons
    NEW_ORDER_CALLBACK_DATA = "NEW_ORDER_CALLBACK_DATA_btn1"
    ACTIVE_ORDERS_CALLBACK_DATA = "ACTIVE_ORDERS_CALLBACK_DATA_btn2"
    MY_PROFILE_CALLBACK_DATA = "MY_PROFILE_CALLBACK_DATA_btn3"
    BALANCE_CALLBACK_DATA = "BALANCE_CALLBACK_DATA_btn4"
    SUPPORT_CALLBACK_DATA = "SUPPORT_CALLBACK_DATA_btn5"
    REVIEWS_CALLBACK_DATA = "REVIEWS_CALLBACK_DATA_btn6"
    AFFILIATE_PROGRAM_CALLBACK_DATA = "AFFILIATE_PROGRAM_CALLBACK_DATA_btn7"
    SOLVER_MENU_CALLBACK_DATA = "SOLVER_MENU_CALLBACK_DATA_btn8"
    PARTNER_CONTROL_PANEL_CALLBACK_DATA = "PARTNER_CONTROL_PANEL_CALLBACK_DATA_btn9"
    ADMIN_CONTROL_PANEL_CALLBACK_DATA = "ADMIN_CONTROL_PANEL_CALLBACK_DATA_btn10"
    ACCOUNTANT_CONTROL_PANEL_CALLBACK_DATA = "ACCOUNTANT_CONTROL_PANEL_CALLBACK_DATA_btn11"
    CREATOR_CONTROL_PANEL_CALLBACK_DATA = "CREATOR_CONTROL_PANEL_CALLBACK_DATA_btn12"
    CUSTOM_MENU_CALLBACK_DATA = "CUSTOM_MENU_CALLBACK_DATA_btn13"
    YES_BUTTON_CALLBACK_DATA = "YES_BUTTON_CALLBACK_DATA_btn14"
    NO_BUTTON_CALLBACK_DATA = "NO_BUTTON_CALLBACK_DATA_btn15"
    USER_SUBSCRIPTION_CHECK_CALLBACK_DATA = "USER_SUBSCRIPTION_CHECK_CALLBACK_DATA_btn16" #проверка на то, что пользователь подписался
    #support menu
    BECOME_A_PARTNER_CALLBACK_DATA = "BECOME_A_PARTNER_CALLBACK_DATA_btn17"
    BECOME_A_SOLVER_CALLBACK_DATA = "BECOME_A_SOLVER_CALLBACK_DATA_btn18"
    ASK_A_QUESTION_CALLBACK_DATA = "ASK_A_QUESTION_CALLBACK_DATA_btn19"
    FAQ_CALLBACK_DATA = "FAQ_CALLBACK_DATA_btn20"
    #balance menu
    CASH_IN_CALLBACK_DATA = "CASH_IN_CALLBACK_DATA_btn21"
    CASH_OUT_CALLBACK_DATA = "CASH_OUT_CALLBACK_DATA_btn22"
    #my profile menu
    SET_BANKING_DETAILS_CALLBACK_DATA = "SET_BANKING_DETAILS_CALLBACK_DATA_btn23"
    SET_CURRENCY_CALLBACK_DATA = "SET_CURRENCY_CALLBACK_DATA_btn24"
    SET_LANGUAGE_CALLBACK_DATA = "SET_LANGUAGE_CALLBACK_DATA_btn25"
    #affiliate program menu
    LIST_AFFILIATE_LINKS_CALLBACK_DATA = "LIST_AFFILIATE_LINKS_CALLBACK_DATA_btn26"
    CREATE_AFFILIATE_LINK_CALLBACK_DATA = "CREATE_AFFILIATE_LINK_CALLBACK_DATA_btn27"
    AFFILIATE_PROGRAM_STATISTICS_CALLBACK_DATA = "AFFILIATE_PROGRAM_STATISTICS_CALLBACK_DATA_btn28"
    #new order menu
    NEW_ORDER_BY_ADMIN_CALLBACK_DATA = "NEW_ORDER_BY_ADMIN_CALLBACK_DATA_btn29"
    NEW_ORDER_BY_BOT_CALLBACK_DATA = "NEW_ORDER_BY_BOT_CALLBACK_DATA_btn30"
    UNFINISHED_ORDER_CALLBACK_DATA = "UNFINISHED_ORDER_CALLBACK_DATA_btn31"
    #new order: order importance menu
    STANDART_IMPORTANCE_CALLBACK_DATA = "STANDART_IMPORTANCE_CALLBACK_DATA_btn32"
    NOW_IMPORTANCE_CALLBACK_DATA = "NOW_IMPORTANCE_CALLBACK_DATA_btn33"
    IMPORTANT_IMPORTANCE_CALLBACK_DATA = "IMPORTANT_IMPORTANCE_CALLBACK_DATA_btn34"
    VOLUMINOUS_IMPORTANCE_CALLBACK_DATA = "VOLUMINOUS_IMPORTANCE_CALLBACK_DATA_btn35"
    #new order menu:    standart order main menu
    NEW_STANDART_ORDER_IMPORTANCE_CALLBACK_DATA = "NEW_STANDART_ORDER_IMPORTANCE_CALLBACK_DATA_btn36"
    NEW_NOW_ORDER_IMPORTANCE_CALLBACK_DATA = "NEW_NOW_ORDER_IMPORTANCE_CALLBACK_DATA_btn193"
    NEW_STANDART_ORDER_SUBJECT_CALLBACK_DATA = "NEW_STANDART_ORDER_SUBJECT_CALLBACK_DATA_btn37"
    NEW_STANDART_ORDER_COMMENT_CALLBACK_DATA = "NEW_STANDART_ORDER_COMMENT_CALLBACK_DATA_btn38"
    NEW_STANDART_ORDER_FILES_CALLBACK_DATA = "NEW_STANDART_ORDER_FILES_CALLBACK_DATA_btn39"
    NEW_STANDART_ORDER_DEADLINE_TIME_CALLBACK_DATA = "NEW_STANDART_ORDER_DEADLINE_TIME_CALLBACK_DATA_btn40"
    NEW_IMPORTANT_ORDER_DURATION_TIME_CALLBACK_DATA = "NEW_IMPORTANT_ORDER_DURATION_TIME_CALLBACK_DATA_btn194"
    NEW_NOW_ORDER_NUMBER_OF_TASKS_CALLBACK_DATA = "NEW_NOW_ORDER_NUMBER_OF_TASKS_CALLBACK_DATA_btn192"
    UP_ORDER_SETTINGS_CALLBACK_DATA = "UP_ORDER_SETTINGS_CALLBACK_DATA_btn152"
    SEND_ORDER_TO_SOLVERS_CALLBACK_DATA = "SEND_ORDER_TO_SOLVERS_CALLBACK_DATA_btn153"
    #get order files
    CONFIRM_FILES_CALLBACK_DATA = "CONFIRM_FILES_CALLBACK_DATA_btn173"
    DELETE_ALL_FILES_CALLBACK_DATA = "DELETE_ALL_FILES_CALLBACK_DATA_btn174"
    #order formats
    CONTROL_FORMAT_CALLBACK_DATA = "CONTROL_FORMAT_CALLBACK_DATA_btn175"
    HOMEWORK_FORMAT_CALLBACK_DATA = "HOMEWORK_FORMAT_CALLBACK_DATA_btn176"
    EXAM_FORMAT_CALLBACK_DATA = "EXAM_FORMAT_CALLBACK_DATA_btn177"
    LABA_FORMAT_CALLBACK_DATA = "LABA_FORMAT_CALLBACK_DATA_btn178"
    COURSEWORK_FORMAT_CALLBACK_DATA = "COURSEWORK_FORMAT_CALLBACK_DATA_btn179"
    DIPLOMA_FORMAT_CALLBACK_DATA = "DIPLOMA_FORMAT_CALLBACK_DATA_btn180"
    OTHER_FORMAT_CALLBACK_DATA = "OTHER_FORMAT_CALLBACK_DATA_btn181"
    #get order percent menu
    TEN_PERCENT_CALLBACK_DATA = "TEN_PERCENT_CALLBACK_DATA_btn182"
    TWENTY_PERCENT_CALLBACK_DATA = "TWENTY_PERCENT_CALLBACK_DATA_btn183"
    THIRTY_PERCENT_CALLBACK_DATA = "THIRTY_PERCENT_CALLBACK_DATA_btn184"
    FORTY_PERCENT_CALLBACK_DATA = "FORTY_PERCENT_CALLBACK_DATA_btn185"
    FIFTY_PERCENT_CALLBACK_DATA = "FIFTY_PERCENT_CALLBACK_DATA_btn186"
    SIXTY_PERCENT_CALLBACK_DATA = "SIXTY_PERCENT_CALLBACK_DATA_btn187"
    SEVENTY_PERCENT_CALLBACK_DATA = "SEVENTY_PERCENT_CALLBACK_DATA_btn188"
    EIGHTY_PERCENT_CALLBACK_DATA = "EIGHTY_PERCENT_CALLBACK_DATA_btn189"
    NINETY_PERCENT_CALLBACK_DATA = "NINETY_PERCENT_CALLBACK_DATA_btn190"
    HUNDRED_PERCENT_CALLBACK_DATA = "HUNDRED_PERCENT_CALLBACK_DATA_btn191"
    #additional order settings menu
    SUPPORT_ORDER_SETTING_CALLBACK_DATA = "SUPPORT_ORDER_SETTING_CALLBACK_DATA_btn154"
    PERCENT_COMPLET_ORDER_SETTING_CALLBACK_DATA = "PERCENT_COMPLET_ORDER_SETTING_CALLBACK_DATA_btn155"
    PREFERRED_BUDGET_ORDER_SETTING_CALLBACK_DATA = "PREFERRED_BUDGET_ORDER_SETTING_CALLBACK_DATA_btn156"
    TYPE_ORDER_SETTING_CALLBACK_DATA = "TYPE_ORDER_SETTING_CALLBACK_DATA_btn157"
    #date keyboard
    DAY_CALLBACK_DATA = "DAY_CALLBACK_DATA"
    LAST_MONTH_CALLBACK_DATA = "LAST_MONTH_CALLBACK_DATA_btn159"
    THIS_MONTH_CALLBACK_DATA = "THIS_MONTH_CALLBACK_DATA_btn160"
    NEXT_MONTH_CALLBACK_DATA = "NEXT_MONTH_CALLBACK_DATA_btn161"
    WEEKDAY_CALLBACK_DATA = "WEEKDAY_CALLBACK_DATA_btn162"
    NONE_DAY_CALLBACK_DATA = "NONE_DAY_CALLBACK_DATA_btn163"
    #get order time
    GET_ORDER_TIME_CALLBACK_DATA = "GET_ORDER_TIME_CALLBACK_DATA_btn164"
    ORDER_1DURATION_CALLBACK_DATA = "ORDER_1DURATION_CALLBACK_DATA_btn165"
    ORDER_2DURATION_CALLBACK_DATA = "ORDER_2DURATION_CALLBACK_DATA_btn166"
    ORDER_3DURATION_CALLBACK_DATA = "ORDER_3DURATION_CALLBACK_DATA_btn167"
    ORDER_4DURATION_CALLBACK_DATA = "ORDER_4DURATION_CALLBACK_DATA_btn168"
    ORDER_5DURATION_CALLBACK_DATA = "ORDER_5DURATION_CALLBACK_DATA_btn169"
    ORDER_6DURATION_CALLBACK_DATA = "ORDER_6DURATION_CALLBACK_DATA_btn170"
    ORDER_7DURATION_CALLBACK_DATA = "ORDER_7DURATION_CALLBACK_DATA_btn171"
    ORDER_8DURATION_CALLBACK_DATA = "ORDER_8DURATION_CALLBACK_DATA_btn172"
    #check order complite to send menu
    TRUE_CHECK_ORDER_COMPLITE_TO_SEND_MENU_CALLBACK_DATA = "TRUE_CHECK_ORDER_COMPLITE_TO_SEND_MENU_CALLBACK_DATA_btn195"
    FALSE_CHECK_ORDER_COMPLITE_TO_SEND_MENU_CALLBACK_DATA = "FALSE_CHECK_ORDER_COMPLITE_TO_SEND_MENU_CALLBACK_DATA_btn196"


    """Orders and topics keyboards:"""
    MATHS_SUBJECT_CALLBACK_DATA = "MATHS_SUBJECT_CALLBACK_DATA_btn41"
    PHYSICS_SUBJECT_CALLBACK_DATA = "PHYSICS_SUBJECT_CALLBACK_DATA_btn42"
    IT_SUBJECT_CALLBACK_DATA = "IT_SUBJECT_CALLBACK_DATA_btn43"
    ENGINEERING_SUBJECT_CALLBACK_DATA = "ENGINEERING_SUBJECT_CALLBACK_DATA_btn44"
    ECONOMY_SUBJECT_CALLBACK_DATA = "ECONOMY_SUBJECT_CALLBACK_DATA_btn45"
    CHEMISTRY_SUBJECT_CALLBACK_DATA = "CHEMISTRY_SUBJECT_CALLBACK_DATA_btn46"
    LANGUAGES_SUBJECT_CALLBACK_DATA = "LANGUAGES_SUBJECT_CALLBACK_DATA_btn47"
    BIOLOGY_SUBJECT_CALLBACK_DATA = "BIOLOGY_SUBJECT_CALLBACK_DATA_btn48"
    GEOGRAPHY_SUBJECT_CALLBACK_DATA = "GEOGRAPHY_SUBJECT_CALLBACK_DATA_btn49"
    HUMANITARIAN_SUBJECT_CALLBACK_DATA = "HUMANITARIAN_SUBJECT_CALLBACK_DATA_btn50"
    REGISTRATION_SUBJECT_CALLBACK_DATA = "REGISTRATION_SUBJECT_CALLBACK_DATA_btn51"
    OTHER_SUBJECT_CALLBACK_DATA = "OTHER_SUBJECT_CALLBACK_DATA_btn52"

    #maths
    CALCULUS_OF_VARIATIONS_CALLBACK_DATA = "CALCULUS_OF_VARIATIONS_CALLBACK_DATA_btn53"
    VECTOR_TENSOR_ANALYSIS_CALLBACK_DATA = "VECTOR_TENSOR_ANALYSIS_CALLBACK_DATA_btn54"
    COMPUTATIONAL_MATHEMATICS_CALLBACK_DATA = "COMPUTATIONAL_MATHEMATICS_CALLBACK_DATA_btn55"
    DISCRETE_MATHEMATICS_CALLBACK_DATA = "DISCRETE_MATHEMATICS_CALLBACK_DATA_btn56"
    DIFFUSIONS_CALLBACK_DATA = "DIFFUSIONS_CALLBACK_DATA_btn57"
    MULTIPLE_INTEGRALS_CALLBACK_DATA = "MULTIPLE_INTEGRALS_CALLBACK_DATA_btn58"
    MATHEMATICAL_ANALYSIS_CALLBACK_DATA = "MATHEMATICAL_ANALYSIS_CALLBACK_DATA_btn59"
    MATHEMATICAL_MODELING_CALLBACK_DATA = "MATHEMATICAL_MODELING_CALLBACK_DATA_btn60"
    SYSTEM_ANALYSIS_AND_DECISION_MAKING_CALLBACK_DATA = "SYSTEM_ANALYSIS_AND_DECISION_MAKING_CALLBACK_DATA_btn61"
    TFCP_CALLBACK_DATA = "TFCP_CALLBACK_DATA_btn62"
    ANALYTICAL_GEOMETRY_CALLBACK_DATA = "ANALYTICAL_GEOMETRY_CALLBACK_DATA_btn63"
    LINEAR_ALGEBRA_CALLBACK_DATA = "LINEAR_ALGEBRA_CALLBACK_DATA_btn64"
    MATHEMATICAL_STATISTICS_CALLBACK_DATA = "MATHEMATICAL_STATISTICS_CALLBACK_DATA_btn65"
    ROWS_CALLBACK_DATA = "ROWS_CALLBACK_DATA_btn66"
    PROBABILITY_THEORY_CALLBACK_DATA = "PROBABILITY_THEORY_CALLBACK_DATA_btn67"
    TOPOLOGY_CALLBACK_DATA = "TOPOLOGY_CALLBACK_DATA_btn68"
    UMF_CALLBACK_DATA = "UMF_CALLBACK_DATA_btn69"
    FUNCTIONAL_ANALYSIS_CALLBACK_DATA = "FUNCTIONAL_ANALYSIS_CALLBACK_DATA_btn70"
    FUNCTIONS_OF_MULTIPLE_VARIABLES_CALLBACK_DATA = "FUNCTIONS_OF_MULTIPLE_VARIABLES_CALLBACK_DATA_btn71"
    OTHER_MATHS_CALLBACK_DATA = "OTHER_MATHS_CALLBACK_DATA_btn72"
    #physics
    QUANTUM_MECHANICS_CALLBACK_DATA = "QUANTUM_MECHANICS_CALLBACK_DATA_btn73"
    MATERIALS_SCIENCE_CALLBACK_DATA = "MATERIALS_SCIENCE_CALLBACK_DATA_btn74"
    METROLOGY_CALLBACK_DATA = "METROLOGY_CALLBACK_DATA_btn75"
    MECHANICS_CALLBACK_DATA = "MECHANICS_CALLBACK_DATA_btn76"
    FLUID_AND_GAS_MECHANICS_CALLBACK_DATA = "FLUID_AND_GAS_MECHANICS_CALLBACK_DATA_btn77"
    OPTICS_CALLBACK_DATA = "OPTICS_CALLBACK_DATA_btn78"
    STRENGTH_OF_MATERIALS_CALLBACK_DATA = "STRENGTH_OF_MATERIALS_CALLBACK_DATA_btn79"
    THEORETICAL_MECHANICS_CALLBACK_DATA = "THEORETICAL_MECHANICS_CALLBACK_DATA_btn80"
    ELECTRICITY_CALLBACK_DATA = "ELECTRICITY_CALLBACK_DATA_btn81"
    OTHER_PHYSICS_CALLBACK_DATA = "OTHER_PHYSICS_CALLBACK_DATA_btn82"
    #IT
    BASIC_IT_CALLBACK_DATA = "BASIC_IT_CALLBACK_DATA_btn83"
    C_IT_CALLBACK_DATA = "C_IT_CALLBACK_DATA_btn84"
    C_SHARP_IT_CALLBACK_DATA = "C_SHARP_IT_CALLBACK_DATA_btn85"
    C_PLUS_PLUS_IT_CALLBACK_DATA = "C_PLUS_PLUS_IT_CALLBACK_DATA_btn86"
    DELPHI_IT_CALLBACK_DATA = "DELPHI_IT_CALLBACK_DATA_btn87"
    EXCEL_IT_CALLBACK_DATA = "EXCEL_IT_CALLBACK_DATA_btn88"
    JAVA_IT_CALLBACK_DATA = "JAVA_IT_CALLBACK_DATA_btn89"
    JAVA_SCRIPT_CALLBACK_DATA = "JAVA_SCRIPT_CALLBACK_DATA_btn90"
    GO_IT_CALLBACK_DATA = "GO_IT_CALLBACK_DATA_btn91"
    MATLAB_IT_CALLBACK_DATA = "MATLAB_IT_CALLBACK_DATA_btn92"
    PYTHON_IT_CALLBACK_DATA = "PYTHON_IT_CALLBACK_DATA_btn93"
    PHP_IT_CALLBACK_DATA = "PHP_IT_CALLBACK_DATA_btn94"
    DATA_BASE_IT_CALLBACK_DATA = "DATA_BASE_IT_CALLBACK_DATA_btn95"
    LATEX_IT_CALLBACK_DATA = "LATEX_IT_CALLBACK_DATA_btn96"
    LAZARUS_CALLBACK_DATA = "LAZARUS_CALLBACK_DATA_btn97"
    PASCAL_IT_CALLBACK_DATA = "PASCAL_IT_CALLBACK_DATA_btn98"
    R_IT_CALLBACK_DATA = "R_IT_CALLBACK_DATA_btn99"
    OTHER_IT_CALLBACK_DATA = "OTHER_IT_CALLBACK_DATA_btn100"
    #engineering
    ENGINEERING_GRAPHICS_CALLBACK_DATA = "ENGINEERING_GRAPHICS_CALLBACK_DATA_btn101"
    DESCRIPTIVE_GEOMETRY_CALLBACK_DATA = "DESCRIPTIVE_GEOMETRY_CALLBACK_DATA_btn102"
    CIRCUITRY_AND_MECHATRONICS_CALLBACK_DATA = "CIRCUITRY_AND_MECHATRONICS_CALLBACK_DATA_btn103"
    THEORY_OF_MECHANISMS_AND_MACHINES_CALLBACK_DATA = "THEORY_OF_MECHANISMS_AND_MACHINES_CALLBACK_DATA_btn104"
    TECHNOLOGY_OF_STRUCTURAL_MATERIALS_CALLBACK_DATA = "TECHNOLOGY_OF_STRUCTURAL_MATERIALS_CALLBACK_DATA_btn105"
    ELECTRONICS_CALLBACK_DATA = "ELECTRONICS_CALLBACK_DATA_btn106"
    ELECTRONIC_BOARDS_AND_COMPONENTS_CALLBACK_DATA = "ELECTRONIC_BOARDS_AND_COMPONENTS_CALLBACK_DATA_btn107"
    ELECTRICAL_ENGINEERING_CALLBACK_DATA = "ELECTRICAL_ENGINEERING_CALLBACK_DATA_btn108"
    ANALYTICAL_MECHANICS_CALLBACK_DATA = "ANALYTICAL_MECHANICS_CALLBACK_DATA_btn109"
    MACHINES_CALLBACK_DATA = "MACHINES_CALLBACK_DATA_btn110"
    OTHER_ENGINEERING_CALLBACK_DATA = "OTHER_ENGINEERING_CALLBACK_DATA_btn111"
    #economy
    LOGISTICS_CALLBACK_DATA = "LOGISTICS_CALLBACK_DATA_btn112"
    MACROECONOMICS_CALLBACK_DATA = "MACROECONOMICS_CALLBACK_DATA_btn113"
    MARKETING_CALLBACK_DATA = "MARKETING_CALLBACK_DATA_btn114"
    MANAGEMENT_CALLBACK_DATA = "MANAGEMENT_CALLBACK_DATA_btn115"
    MICROECONOMICS_CALLBACK_DATA = "MICROECONOMICS_CALLBACK_DATA_btn116"
    TAXATION_CALLBACK_DATA = "TAXATION_CALLBACK_DATA_btn117"
    PERSONNEL_MANAGEMENT_CALLBACK_DATA = "PERSONNEL_MANAGEMENT_CALLBACK_DATA_btn118"
    ECONOMY_CALLBACK_DATA = "ECONOMY_CALLBACK_DATA_btn119"
    ACCOUNTING_CALLBACK_DATA = "ACCOUNTING_CALLBACK_DATA_btn120"
    ECONOMETRICS_CALLBACK_DATA = "ECONOMETRICS_CALLBACK_DATA_btn121"
    OTHER_ECONOMY_CALLBACK_DATA = "OTHER_ECONOMY_CALLBACK_DATA_btn122"
    #chemistry
    ORGANIC_CHEMISTRY_CALLBACK_DATA = "ORGANIC_CHEMISTRY_CALLBACK_DATA_btn122"
    ANALYTICAL_CHEMISTRY_CALLBACK_DATA = "ANALYTICAL_CHEMISTRY_CALLBACK_DATA_btn123"
    GENERAL_CHEMISTRY_CALLBACK_DATA = "GENERAL_CHEMISTRY_CALLBACK_DATA_btn124"
    BIOCHEMISTRY_CALLBACK_DATA = "BIOCHEMISTRY_CALLBACK_DATA_btn125"
    PHYSICAL_CHEMISTRY_CALLBACK_DATA = "PHYSICAL_CHEMISTRY_CALLBACK_DATA_btn126"
    INORGANIC_CHEMISTRY_CALLBACK_DATA = "INORGANIC_CHEMISTRY_CALLBACK_DATA_btn127"
    OTHER_CHEMISTRY_CALLBACK_DATA = "OTHER_CHEMISTRY_CALLBACK_DATA_btn128"
    #languages
    RUSSIAN_CALLBACK_DATA = "RUSSIAN_CALLBACK_DATA_btn129"
    CHINESE_CALLBACK_DATA = "CHINESE_CALLBACK_DATA_btn130"
    ENGLISH_CALLBACK_DATA = "ENGLISH_CALLBACK_DATA_btn131"
    FRENCH_CALLBACK_DATA= "FRENCH_CALLBACK_DATA_btn132"
    GERMAN_CALLBACK_DATA= "GERMAN_CALLBACK_DATA_btn133"
    SPANISH_CALLBACK_DATA = "SPANISH_CALLBACK_DATA_btn134"
    OTHER_LANGUAGES_CALLBACK_DATA = "OTHER_LANGUAGES_CALLBACK_DATA_btn135"
    #biology
    ANATOMY_CALLBACK_DATA = "ANATOMY_CALLBACK_DATA_btn135"
    PARASITOLOGY_CALLBACK_DATA = "PARASITOLOGY_CALLBACK_DATA_btn136"
    BIOINFORMATICS_CALLBACK_DATA = "BIOINFORMATICS_CALLBACK_DATA_btn137"
    MICROBIOLOGY_CALLBACK_DATA = "MICROBIOLOGY_CALLBACK_DATA_btn138"
    BOTANY_CALLBACK_DATA = "BOTANY_CALLBACK_DATA_btn139"
    MOLECULAR_BIOLOGY_CALLBACK_DATA = "MOLECULAR_BIOLOGY_CALLBACK_DATA_btn140"
    ZOOLOGY_CALLBACK_DATA = "ZOOLOGY_CALLBACK_DATA_btn141"
    GENETICS_CALLBACK_DATA = "GENETICS_CALLBACK_DATA_btn142"
    VIROLOGY_CALLBACK_DATA = "VIROLOGY_CALLBACK_DATA_btn143"
    OTHER_BIOLOGY_CALLBACK_DATA = "OTHER_BIOLOGY_CALLBACK_DATA_btn144"
    #geography
    GEOGRAPHY_CALLBACK_DATA = "GEOGRAPHY_CALLBACK_DATA_btn145"
    #humanitarian
    HISTORY_CALLBACK_DATA = "HISTORY_CALLBACK_DATA_btn145"
    DESIGN_CALLBACK_DATA = "DESIGN_CALLBACK_DATA_btn146"
    OBZH_CALLBACK_DATA = "OBZH_CALLBACK_DATA_btn147"
    PHILOSOPHY_CALLBACK_DATA = "PHILOSOPHY_CALLBACK_DATA_btn148"
    LAW_CALLBACK_DATA = "LAW_CALLBACK_DATA_btn149"
    OTHER_HUMANITARIAN_CALLBACK_DATA = "OTHER_HUMANITARIAN_CALLBACK_DATA_btn150"
    #registration
    REGISTRATION_CALLBACK_DATA = "REGISTRATION_CALLBACK_DATA_btn151"


class ButtonURLData:
    FAQ_FOR_CLIENTS_URL_DATA = "https://yandex.ru/"
    FAQ_FOR_SOLVERS_URL_DATA = "https://yandex.ru/"
    FAQ_FOR_PARTNERS_URL_DATA = "https://yandex.ru/"